"""Flash Attention CUTE (CUDA Template Engine) implementation."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("fa4")
except PackageNotFoundError:
    __version__ = "0.0.0"

import cutlass.cute as cute

from .interface import (
    flash_attn_func,
    flash_attn_mixed_local_hsa_func,
    flash_attn_varlen_func,
)
from .hsa import (
    HSASchedule,
    backward_packed_masks_to_attend_mask,
    backward_descriptors_to_attend_mask,
    build_hsa_schedule,
    build_hsa_schedule_from_support,
    build_hsa_schedule_from_sum_tok_metadata,
    build_hsa_sum_tok_schedule,
    compute_hsa_mask,
    compute_hsa_sum_tok_mask,
    flash_attn_hsa_func,
    flash_attn_hsa_sparse_func,
    fused_forward_to_attend_mask,
    forward_descriptors_to_attend_mask,
    forward_tile_masks_to_attend_mask,
    get_hsa_mask_mod,
    hybrid_backward_to_attend_mask,
    hsa_reference_attention,
    hsa_sparse_reference_attention,
    infer_hsa_sum_tok_metadata,
    schedule_to_attend_mask,
)
from .hsa_sparse24_analysis import (
    analyze_hsa_sparse24_feasibility,
    summarize_hsa_sparse24_feasibility,
)
from .hsa_approx_sparse_gemm_analysis import (
    analyze_hsa_approx_sparse_gemm_forward,
    summarize_hsa_approx_sparse_gemm_forward,
)
from .hsa_shared_sparse_gemm_analysis import (
    analyze_hsa_shared_sparse_gemm_forward,
    summarize_hsa_shared_sparse_gemm_forward,
)
from .hsa_explicit_2d_sparse_analysis import (
    analyze_explicit_2d_sparse_forward,
    build_explicit_2d_sparse_case,
    scatter_explicit_packed_rows,
    summarize_explicit_2d_sparse_forward,
    summarize_explicit_2d_sparse_suite,
)
from .hsa_cached_2d_forward_analysis import (
    CachedPackingPolicy,
    build_cached_direct_2d_forward_payload,
    build_cached_generalized_packed_forward_payload,
    run_cached_direct_2d_forward,
    run_cached_generalized_packed_forward,
)
from .arhsa_walk_sm100 import (
    arhsa_row_gather_2d_autograd,
    arhsa_trusted_row_write_2d_autograd,
    arhsa_v3_walk_readout_from_scores_fixed_iters_autograd,
    arhsa_walk_readout_from_scores_fixed_iters_autograd,
    build_incoming_edge_csr,
    build_outgoing_edge_csr,
    build_query_leaf_csr,
    outgoing_softmax_from_scores,
    readout_arhsa_leaf_attention,
    run_arhsa_gather_edge_prob_by_index,
    run_arhsa_child_gat_state_forward,
    run_arhsa_child_gat_kv_projection,
    run_arhsa_child_gat_kv_projection_small,
    run_arhsa_child_gat_score_reduce,
    run_arhsa_child_gat_score_reduce_backward,
    run_arhsa_child_gat_state_forward_tma_pipeline,
    run_arhsa_dense_gemm_128,
    run_arhsa_v3_start_score_forward,
    run_arhsa_v3_start_initial_state_backward,
    run_arhsa_v3_start_initial_state_forward,
    run_arhsa_v3_start_open_scores_forward,
    run_arhsa_key_projection_norm_write,
    run_arhsa_key_projection_postprocess,
    run_arhsa_leaf_readout,
    run_arhsa_leaf_readout_backward,
    run_arhsa_out_projection_write,
    run_arhsa_projection_norm_write_small,
    run_arhsa_pack_leaf_values,
    run_arhsa_markov_backward_step,
    run_arhsa_markov_backward_range_step,
    run_arhsa_markov_incoming_step,
    run_arhsa_markov_incoming_packed_step,
    run_arhsa_markov_incoming_packed_range_step,
    run_arhsa_markov_walk_fixed_iters,
    run_arhsa_outgoing_softmax,
    run_arhsa_outgoing_softmax_with_incoming,
    run_arhsa_outgoing_softmax_backward,
    run_arhsa_row_gather_2d,
    run_arhsa_row_gather_layer_norm,
    run_arhsa_row_gather_2d_backward,
    run_arhsa_row_write_2d_,
    run_arhsa_walk_readout_from_scores_fixed_iters_backward,
    run_arhsa_walk_readout_from_scores_fixed_iters,
    run_arhsa_walk_readout_fixed_iters,
    torch_arhsa_markov_walk_fixed_iters,
    torch_arhsa_walk_readout_from_scores_fixed_iters_backward,
    torch_arhsa_walk_readout_from_scores_fixed_iters,
)

from flash_attn.cute.cute_dsl_utils import cute_compile_patched

# Patch cute.compile to optionally dump SASS
cute.compile = cute_compile_patched


__all__ = [
    "flash_attn_func",
    "flash_attn_mixed_local_hsa_func",
    "flash_attn_varlen_func",
    "flash_attn_hsa_func",
    "flash_attn_hsa_sparse_func",
    "get_hsa_mask_mod",
    "build_hsa_schedule",
    "build_hsa_schedule_from_support",
    "build_hsa_schedule_from_sum_tok_metadata",
    "build_hsa_sum_tok_schedule",
    "schedule_to_attend_mask",
    "forward_descriptors_to_attend_mask",
    "forward_tile_masks_to_attend_mask",
    "fused_forward_to_attend_mask",
    "backward_descriptors_to_attend_mask",
    "backward_packed_masks_to_attend_mask",
    "hybrid_backward_to_attend_mask",
    "compute_hsa_mask",
    "compute_hsa_sum_tok_mask",
    "infer_hsa_sum_tok_metadata",
    "hsa_reference_attention",
    "hsa_sparse_reference_attention",
    "HSASchedule",
    "analyze_hsa_sparse24_feasibility",
    "summarize_hsa_sparse24_feasibility",
    "analyze_hsa_approx_sparse_gemm_forward",
    "summarize_hsa_approx_sparse_gemm_forward",
    "analyze_hsa_shared_sparse_gemm_forward",
    "summarize_hsa_shared_sparse_gemm_forward",
    "analyze_explicit_2d_sparse_forward",
    "build_explicit_2d_sparse_case",
    "CachedPackingPolicy",
    "build_cached_direct_2d_forward_payload",
    "build_cached_generalized_packed_forward_payload",
    "scatter_explicit_packed_rows",
    "run_cached_direct_2d_forward",
    "run_cached_generalized_packed_forward",
    "build_incoming_edge_csr",
    "build_outgoing_edge_csr",
    "build_query_leaf_csr",
    "outgoing_softmax_from_scores",
    "readout_arhsa_leaf_attention",
    "run_arhsa_leaf_readout",
    "run_arhsa_leaf_readout_backward",
    "run_arhsa_pack_leaf_values",
    "run_arhsa_markov_backward_step",
    "run_arhsa_markov_backward_range_step",
    "run_arhsa_markov_incoming_step",
    "run_arhsa_markov_incoming_packed_step",
    "run_arhsa_markov_incoming_packed_range_step",
    "run_arhsa_gather_edge_prob_by_index",
    "run_arhsa_child_gat_state_forward",
    "run_arhsa_child_gat_kv_projection",
    "run_arhsa_child_gat_kv_projection_small",
    "run_arhsa_child_gat_score_reduce",
    "run_arhsa_child_gat_score_reduce_backward",
    "run_arhsa_child_gat_state_forward_tma_pipeline",
    "run_arhsa_dense_gemm_128",
    "run_arhsa_v3_start_score_forward",
    "run_arhsa_v3_start_initial_state_backward",
    "run_arhsa_v3_start_initial_state_forward",
    "run_arhsa_v3_start_open_scores_forward",
    "run_arhsa_key_projection_norm_write",
    "run_arhsa_key_projection_postprocess",
    "run_arhsa_markov_walk_fixed_iters",
    "run_arhsa_out_projection_write",
    "run_arhsa_projection_norm_write_small",
    "run_arhsa_outgoing_softmax",
    "run_arhsa_outgoing_softmax_with_incoming",
    "run_arhsa_outgoing_softmax_backward",
    "run_arhsa_row_gather_2d",
    "run_arhsa_row_gather_layer_norm",
    "run_arhsa_row_gather_2d_backward",
    "run_arhsa_row_write_2d_",
    "run_arhsa_walk_readout_from_scores_fixed_iters_backward",
    "run_arhsa_walk_readout_from_scores_fixed_iters",
    "run_arhsa_walk_readout_fixed_iters",
    "torch_arhsa_markov_walk_fixed_iters",
    "torch_arhsa_walk_readout_from_scores_fixed_iters_backward",
    "torch_arhsa_walk_readout_from_scores_fixed_iters",
    "arhsa_v3_walk_readout_from_scores_fixed_iters_autograd",
    "arhsa_walk_readout_from_scores_fixed_iters_autograd",
    "arhsa_row_gather_2d_autograd",
    "arhsa_trusted_row_write_2d_autograd",
    "summarize_explicit_2d_sparse_forward",
    "summarize_explicit_2d_sparse_suite",
]
